# Generated by Django 5.1.5 on 2025-02-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タブ名')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='リンク先URL')),
                ('is_displayed', models.BooleanField(default=False, verbose_name='サイトに表示する')),
            ],
        ),
    ]
