# Generated by Django 5.1.5 on 2025-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('category', models.CharField(choices=[('cat1', 'Category 1'), ('cat2', 'Category 2'), ('cat3', 'Category 3'), ('cat4', 'Category 4'), ('cat5', 'Category 5'), ('cat6', 'Category 6'), ('cat7', 'Category 7'), ('cat8', 'Category 8'), ('cat9', 'Category 9'), ('cat10', 'Category 10')], default='cat1', max_length=10, verbose_name='カテゴリ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='記事画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ニュース記事',
                'verbose_name_plural': 'ニュース記事一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='サイトURL')),
                ('site_name', models.CharField(max_length=100, verbose_name='サイト名')),
                ('selector', models.CharField(blank=True, max_length=255, null=True, verbose_name='スクレイピングセレクタ')),
            ],
        ),
    ]
