# Generated by Django 5.1.5 on 2025-02-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newsarticle_scrapingtarget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tab',
        ),
    ]
