# Generated by Django 5.1.5 on 2025-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='元記事URL'),
        ),
    ]
