# Generated by Django 5.1.5 on 2025-02-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=2, verbose_name='性別'),
        ),
    ]
