# Generated by Django 5.1.5 on 2025-02-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, '高'), (2, '中'), (1, '下')], default=2),
        ),
    ]
